### ISSUE TITLE
对 06/07 两章的一些校对

### ISSUE THREAD

**Issue by spacewander** [CodingGirlsClub/python-101-tutorial#2]
06 章
https://coding-girls-club.gitbook.io/python-101/06-python-html
>     question = matched_elements[0].text # element.text 是

此处 “是” 后面缺乏内容

07 章
https://coding-girls-club.gitbook.io/python-101/07-login-and-js-render
> 道德问题：一般爬虫又。爬虫不要给网站就带来太大的负担，影响网站的服务和其他正常用户。

这里有点语法问题

**Comment by luikore** [comment]
已修补
