### ISSUE TITLE
学生应该自学哪些HTML知识点

### ISSUE THREAD

**Issue by sundevilyang** [CodingGirlsClub/python-101-tutorial#4]
在自学任务中，https://coding-girls-club.gitbook.io/python-101/kickoff/3-pre-homework

我们要求学生提前自学HTML，但爬虫并不需要了解那么多知识点。

我们需要把跟爬虫相关的HTML知识点挑出来，节省学生的学习成本 

http://www.w3school.com.cn/html/index.asp

@luikore

**Comment by luikore** [comment]
需要了解的是:

- 常见元素(div, a, img)
- 常见属性(id, class, href, src)
- 选择器

但选择器也不需要了解很多，因为可以直接用 Chrome 的检查元素把想要的选择器挑出来。

**Comment by luikore** [comment]
已添加
